# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: doodle

  # A short description of the repository that will show up on GitHub
  description: cook-a-doodle-doo

  # A URL with more information about the repository
  #homepage: https://example.github.io/

  # A comma-separated list of topics to set on the repository
  #topics: github, probot

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false

  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: true

  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: iOS
    color: f8d4ce
  - name: Android
    color: a0cfa2
  - name: app
    color: 92ceee
  - name: Firebase
    color: ffdac1
  - name: build
    color: b5ead7
  - name: ci
    color: b5ead7
  - name: doc
    color: daf0ee
  - name: test
    color: daf0ee
  - name: feature
    description: A new feature.
    color: c3e8b5
  - name: bug
    description: A bug fix.
    color: ff9aa2
  - name: improvement
    description: An improvement to a current feature.
    color: c3e8b5
  - name: chore
    color: ffeeb8
  - name: performance
    description: A code change that improves performance.
    color: c3e8b5
  - name: BREAKING CHANGE
    description: Breaking change.
    color: 3f3f3f
  - name: deps
    description: Bump dependency version.
    color: eeeeee
  - name: duplicate
    description: This issue or pull request already exists.
    color: eeeeee
  - name: good first issue
    description: Good for newcomers.
    color: 9eabd6
  - name: help wanted
    description: Extra attention is needed.
    color: dfc6de
  - name: invalid
    description: This doesn't seem right.
    color: eeeeee
  - name: question
    description: Further information is requested.
    color: 9eabd6
  - name: wontfix
    description: This will not be worked on.
    color: 3f3f3f
  - name: skip-auto-complete
    description: Prevent pull requests from being merged automatically.
    color: ffffff
  - name: skip-release-note
    description: Prevent creating release note draft from pull request.
    color: ffffff
#  - name: first-timers-only
#    # include the old name to rename and existing label
#    old_name: Help Wanted

# Milestones: define milestones for Issues and Pull Requests
milestones: []

# Collaborators: give specific users access to this repository.
collaborators: []

# See https://developer.github.com/v3/teams/#add-or-update-team-repository for available options
teams: []

branches:
  - name: 'main'
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews: null
      #  # The number of approvals required. (1-6)
      #  required_approving_review_count: 1
      #  # Dismiss approved reviews automatically when a new commit is pushed.
      #  dismiss_stale_reviews: true
      #  # Blocks merge until code owners have reviewed.
      #  require_code_owner_reviews: false
      #  # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
      #  dismissal_restrictions:
      #    users: []
      #    teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts:
          - WIP
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions: null # Disabled to allow merging by automerge-action
      #  apps: []
      #  users: []
      #  teams: []
